@extends('layouts.default')

@section('content')
    <div class="row">
            <h1>Restaurant Menu Boards, Displays, and Directional Signs</h1>
            <p>We have the experience and know-how to <em>design, build and install lighted</em> <strong>outdoor menus</strong> that perform well under the demands of climate elements and years of service. We also make <strong>indoor menu display boards</strong> that are attractive and effectively promote your products. When it comes to restaurants and cafés, we understand the importance of presentation and attention to detail that speaks well of your store's image. Our Columbus Ohio sign facilities offer some of the most innovative and advanced techniques in building restaurant menus. Whether your project requires one menu or a hundred, we can accommodate any order size. With nearly five decades of experience in our sign shop, you can simply tell us the type of custom menu you want and how you want it installed and we will take care of the project, start to finish. We provide our customers with a stress-free, single-source solution that results in consistent customer satisfaction and a high incidence of repeat orders.</p>
            <p>Some types of premium <strong>Restaurant Menu Board Systems</strong> we manufacture, which are available in multiple configurations (see sample images, below):</p>
            <p><strong>- Illuminated or non-illuminated</strong><strong><br> - Exterior or interior boards<br> - Post or wall mounted<br> - Preview/pre-sell boards<br> - Speaker posts &amp; canopy<br> - Customized with your graphics and color schemes</strong></p>
            <h3>Directional or Wayfinding Signs</h3>
            <p><strong>Directional Signs</strong> are often the first communications you have with a customer or client, therefore, they are an important but often overlooked first impression about your business.&nbsp;Directional signs are deployed in and around your commercial property to <strong>direct the flow of traffic</strong>&nbsp;to your business, around parking areas, into designated areas, such as customer entrances, drive-thru lanes, employee parking, and shipping and loading zones.</p>
            <p style="text-align: center; margin-top: 25px;">
              <a href="https://customsigncenter.com/images/Donotos-Pizza-L.jpg" target="_blank" rel="lightbox noopener noreferrer" class="jcepopup jcemediabox-image" title="Donotos Pizza" data-mediabox="1" data-mediabox-group="lightbox" data-mediabox-title="Donatos Pizza " data-mediabox-caption="Donatos Pizza Interior Menu Boards"><img src="https://customsigncenter.com/images/Donotos-Pizza-H.jpg" alt="Donotos Pizza H" style="margin-top: 5px; margin-bottom: 5px;" title="Donotos Pizza"></a> <a href="https://customsigncenter.com/images/Feta-Menu-L.jpg" target="_blank" rel="lightbox noopener noreferrer" class="jcepopup" title="Feta Greek Kuzina" data-mediabox="1" data-mediabox-group="lightbox" data-mediabox-caption="Feta Greek Drive-Thru Menuboard">&nbsp; <img src="https://customsigncenter.com/images/Feta-Menu-T.jpg" alt="Feta Menu T" style="margin-top: 5px; margin-bottom: 5px;" title="Feta Greek Kuzina"></a> &nbsp; <a href="https://customsigncenter.com/images/Tims-L.jpg" target="_blank" rel="lightbox noopener noreferrer" class="jcepopup jcemediabox-image" title="Tim Hortons &amp; Coldstone" data-mediabox-caption="Tim Hortons &amp; Coldstone Drive-Thru Menus" data-mediabox-group="lightbox"><img src="https://customsigncenter.com/images/Tims-T.jpg" alt="Tims T" style="margin-top: 5px; margin-bottom: 5px;" title="Pizza Rustica Outdoor Menu Display for Customer Drive Through Orders"></a> <a href="https://customsigncenter.com/images/Iguanas-Menu-Board.gif" target="_blank" rel="lightbox noopener noreferrer" class="jcepopup" title="Feta Greek Kuzina" data-mediabox="1" data-mediabox-group="lightbox" data-mediabox-title="Iguana's Mexican Restaurant" data-mediabox-caption="Beautiful New Menu Board for Iguana's">&nbsp; <img src="https://customsigncenter.com/images/Iguanas-Menu-Board.gif" alt="Iguanas Menu Board" style="margin-top: 5px; margin-bottom: 5px;" title="Feta Greek Kuzina" width="170" height="128"></a> &nbsp;</p>
          </div>
@stop