@extends('layouts.default')

@section('content')
            <h1 style="text-align: left;">Magnetic Signs</h1>
            <p>Custom Sign Center is Columbus Ohio’s number one source for all your sign needs, that’s why businesses of all sizes have relied on our company for over 40 years! Not only do we make custom signs for business locations, we also help companies take their businesses on the road with custom <a href="https://shop.customsigncenter.com/vehicle-graphics-main-88/categories/" target="_blank" rel="noopener" title="Graphics for one or a whole fleet of Trucks, Vans, Box Trucks Graphics and More!">vehicle graphics</a> and <strong>Magnetic Signs</strong>.&nbsp; Vehicle signage is the fastest and one of the most effective ways to advertise your business. <br><br> Customize affordable car door magnets from Custom Sign Center, with photos, logos, and contact information to reach your customers. Auto door magnets give your company vehicles a professional look while effectively branding and building your brand. <br><br></p>
            <h2>Create your own car and truck magnets online.</h2>
            <p>We can custom-cut a magnetic sign into any desired shape; just call our showroom to speak with a sales associate. Prefer to design your own online? In addition to custom orders, we currently offer four "design-it-online” stock shapes, Including:</p>
            <div style="padding-left: 30px;"><strong><a href="https://shop.customsigncenter.com/car-door-magnets/" target="_blank" rel="noopener" title="Standard Magnetic Signs for Your Vehicle and More!"><br>Standard Magnets </a></strong>– The most popular car magnetic sign is the rectangle style that is available in multiple sizes. Add custom graphics, logos, and information to your sign for one low price. The <strong>standard 12x24 car magnet starts at $29.97</strong>.</div>
            <div style="padding-left: 30px;"><strong><a href="https://shop.customsigncenter.com/car-door-magnets-round/" target="_blank" rel="noopener" title="Round Magnetic Signs for Your Vehicle and More!"><br>Round Magnets </a></strong>– Our online circular magnetic templates offer a range of sizes from 6 to 24 inches in diameter. Full-color prices start <strong>as low as $12.91</strong>, and quantity discount pricing is offered.</div>
            <div style="padding-left: 30px;"><strong><a href="https://shop.customsigncenter.com/car-door-magnets-oval-pairs/" target="_blank" rel="noopener" title="Oval Magnetic Signs for Your Vehicle and More!"><br>Oval Magnets </a></strong>– Use our online design tool to create custom oval magnets. Sizes range from 5x10 to 12x24. Don’t see the size you need? Call our Showroom at 614.279.6035. <strong>Prices as low as $19.19</strong><br><br></div>
            <div style="padding-left: 30px;"><strong>Reflective Magnets </strong>– reflective vehicle magnets are specially made magnetic signs for night use. Use 12x22 standard size signs to illuminate your company’s mobile advertisement. Standard size pricing starting at just <strong>$37.52</strong>.&nbsp; Call our Showroom at 614.279.6035.</div>
            <p><br>You can order <strong>a custom-cut magnetic sign</strong> through our showroom. Visit us in person at <strong>400 Wilson Rd</strong> on the West Side of Columbus, call <strong>(614) 279-6035</strong>, or use our <strong>online design tool</strong> to create custom magnet signs in as little as 5 minutes! Every custom magnet fabricated in our facility is printed in full color with digital UV ink to protect your sign from solar fading. Transform your personal vehicle, company van, or corporate fleet and promote your company while you travel. <br><br></p>
            <h3>Call in and Order a Custom Magnetic Sign, or Create a Magnetic Sign Online:</h3>
            <p><br><br></p>
            <div class="row-fluid">
              <div class="col-md-3"><span class="mag">&nbsp;<a href="https://shop.customsigncenter.com/car-door-magnets/" target="_blank" rel="noopener" hreflang="en-GB" dir="ltr" title="Standard Magnetic Signs for Your Vehicle and More!" lang="en-GB"><img src="https://customsigncenter.com/images/reflective_magnet.jpg" alt="reflective magnet"></a><br><span class="mag"><a href="https://shop.customsigncenter.com/car-door-magnets/" target="_blank" rel="noopener" title="Standard Magnetic Signs for Your Vehicle and More!">STANDARD</a></span></span><br><br></div>
              <div class="col-md-3"><a href="https://shop.customsigncenter.com/car-door-magnets-round/" target="_blank" rel="noopener" title="Round Magnetic Signs You Design"><img src="https://customsigncenter.com/images/Round_Magnet.jpg" alt="Round Magnet"></a> <br> <span class="mag"><a href="https://shop.customsigncenter.com/car-door-magnets-round/" target="_blank" rel="noopener" title="Round Magnetic Signs for Your Vehicle and More!">ROUNDED</a></span></div>
              <div class="col-md-3"><a href="https://shop.customsigncenter.com/car-door-magnets-oval-pairs/" target="_blank" rel="noopener" title="Oval Magnetic Signs for Your Vehicle and More!"><img src="https://customsigncenter.com/images/oval_magnet.jpg" alt="oval magnet"></a> <br> <span class="mag"><a href="https://shop.customsigncenter.com/car-door-magnets-oval-pairs/" target="_blank" rel="noopener" class="mag" title="Oval Magnetic Signs for Your Vehicle and More!">OVAL</a></span></div>
              <div class="col-md-3"><span class="mag"></span> <span id="cloak6b84f38d3f26ce31173b65f0ad52a26b"><a href="mailto:careteam@customsigncenter.com?subject=Reflective%20Magnetic%20Sign&amp;body=I%20am%20interested%20in%20a%20reflective%20magnetic%20sign." target="_blank" hreflang="en-GB" dir="ltr" title="Email the Showroom for More Information" lang="en-GB"><img src="https://customsigncenter.com/images/magnetic_sign.jpg" alt="magnetic sign"></a></span>
                <script type="text/javascript">
                  document.getElementById( 'cloak6b84f38d3f26ce31173b65f0ad52a26b' ).innerHTML = '';
                  var prefix = 'ma' + 'il' + 'to';
                  var path = 'hr' + 'ef' + '=';
                  var addy6b84f38d3f26ce31173b65f0ad52a26b = 'careteam' + '@';
                  addy6b84f38d3f26ce31173b65f0ad52a26b = addy6b84f38d3f26ce31173b65f0ad52a26b + 'customsigncenter' + '.' + 'com?subject=Reflective%20Magnetic%20Sign&body=I%20am%20interested%20in%20a%20reflective%20magnetic%20sign' + '.' + '';
                  var addy_text6b84f38d3f26ce31173b65f0ad52a26b = '<img src="https://customsigncenter.com/images/magnetic_sign.jpg" alt="magnetic sign" />';
                  document.getElementById( 'cloak6b84f38d3f26ce31173b65f0ad52a26b' ).innerHTML += '<a ' + path + '\'' + prefix + ':' + addy6b84f38d3f26ce31173b65f0ad52a26b + '\' target="_blank" hreflang="en-GB" dir="ltr" lang="en-GB" title="Email the Showroom for More Information">' + addy_text6b84f38d3f26ce31173b65f0ad52a26b + '<\/a>';
                </script><span class="mag"></span> <span class="mag">REFLECTIVE</span>Need help designing the perfect car magnet? <a href="/component/k2/item/749" target="_blank" title="Design assistance for your magnetic signs">Click here to read more about designing an effective car magnet.</a>
              </div>
            </div>
            <h3>Why choose magnetic signs?</h3>
            <p>Magnetic signs are a great way to get maximum exposure for your company at a low cost. If you are a local business in pursuit of new customers, magnetic signs may be the perfect solution for you. You’re signs can provide marketing day or night. Even while your vehicles are parked they have the ability to make a huge impression on potential customers. Brand your company vehicles and take your business with you, wherever you go! &nbsp;Magnetic signs are easy to install, remove, and re apply. <br><br> Custom car and vehicle magnets are a great way to add promotional and seasonal advertising to your fleet. A landscaping company may want to advertise professional snow plowing services in the winter or leaf clean up in the fall. &nbsp;Their ability to be interchangeable makes magnetic door signs ideal for all businesses big or small. When cared for properly magnets can last up to 12 months and withstand the outdoor elements. <a href="/component/k2/item/382">Learn how to properly care for your car magnets.</a><br><br> Consider adding vehicle magnets to both sides of your vehicle for maximum exposure and take advantage of our special quantity discounts! Have fun with your car magnets. Personalize your sign to show pride in your alma mater, family member(s), or favorite sports team.. Create custom pet magnets, or dedicate your car magnet to a special cause. Whatever you choose, it’s easy to do with our online design tool! <br><br> Affordable, professional and effective, magnetic signs&nbsp;are a <strong>highly durable and cost effective</strong> way to promote name recognition with your vehicle. You can personalize them in any way from simple letters and logos on basic shapes to digitally printed graphics cut to custom shapes. An extra feature of magnetic signs&nbsp;is that they are <strong>easy to apply and remove</strong> whenever you want. <br><br> Magnetic signs offer a <strong>quick way to turn your vehicle into a marketing tool!</strong>
          </p>
           
                <div class="row-fluid">
                  <div class="col-md-3"><a class="jcepopup" title="McIntosh AG Logistics new Oval Magnetic Signs" href="https://customsigncenter.com/images/phocagallery/DorianMartelOrder667205.jpg" target="_blank" rel="noreferrer noopener" data-mediabox="1" data-mediabox-group="magsigns" data-mediabox-title="McIntosh AG Logistics new Oval Magnetic Signs" data-mediabox-caption="Great signs for their trucks"><img style="margin-bottom: 15px; margin-right: 10px;" src="https://customsigncenter.com/images/phocagallery/0000667205_1-hires_design.jpg" alt="McIntosh AG Logistics Oval Magnet" width="200" height="100"> </a></div>
                  <div class="col-md-3"><a class="jcepopup jcemediabox-image" dir="ltr" title="Paintless Dent Repair Magnetic Sign" href="https://customsigncenter.com/images/phocagallery/DavidMashburgn666094.jpg" hreflang="en-GB" data-mediabox="1" data-mediabox-group="magsigns" data-mediabox-title="David Mashburn's Paintless Dent Repair Magnetic Sign" data-mediabox-caption="Call David to get your dents repaired. Let him know his sign looks great!" lang="en-GB"><img style="margin-right: 10px; margin-bottom: 15px;" title="David Mashburn's Paintless Dent Repair Magnetic Sign" src="https://customsigncenter.com/images/phocagallery/DavidMashburgn666094.jpg" alt="David Mashburn's Magnetic for his Paintless Dent Repair." longdesc="Paintless Dent Repair by David Mashburn" width="200" height="100"></a></div>
                  <div class="col-md-3"><a class="jcepopup jcemediabox-image" dir="ltr" href="https://customsigncenter.com/images/phocagallery/AmyDarling-paper-bag-floewr-co.png" hreflang="en-GB" data-mediabox="1" data-mediabox-group="magsigns" data-mediabox-title="Amy Darling The Paper Bag Flower Company" data-mediabox-caption="Stunning logo for the side of Amy's vehicle." lang="en-GB"><img style="margin-left: 50px; margin-bottom: 15px;" title="Amy Darling The Paper Bag Flower Company" src="https://customsigncenter.com/images/phocagallery/AmyDarling-paper-bag-floewr-co.jpg" alt="Amy Darling Paper Bag Flower Company" longdesc="Tim Hortons Custom Commercial Awnings" width="100" height="100"></a></div>
                  <div class="col-md-3"><a class="jcepopup jcemediabox-image" href="https://customsigncenter.com/images/BasementDoctor.png" target="_blank" rel="noreferrer noopener" data-mediabox="1" data-mediabox-group="magsigns" data-mediabox-title="Ron Grenbaum, The Basement Doctor" data-mediabox-caption="Ron get's a lot of attention with these little beauties. Design yours Today!"><img style="margin-right: 10px; margin-bottom: 15px;" title="Tim Horton's Cafe &amp; Bake Shop Awning" src="https://customsigncenter.com/images/BasementDoctor.png" alt="Ron Greenbaum The Basement Doctor" width="200" height="100"></a>&nbsp;</div>
                </div>             
@stop