@extends('layouts.default')

@section('content')
            <h1>Custom Vinyl Banners You Personalize</h1>
            <p class="mb-4">Our full color <strong>custom vinyl banners</strong> are perfect when it comes to promoting your business or making an important announcement such as a graduation, new baby's arrival, wedding, anniversary, or family/class reunion!&nbsp;&nbsp; We have design templates to fit all your needs!&nbsp;Our digitally printed full color custom vinyl banners are printed on our industry-leading cutting edge machines!</p>
            <p class="mb-4">Your signs are printed on 13 oz scrim vinyl. Scrim vinyl is made of polyester mesh which provides added strength and a smoother texture for printing. Banners are printed in full color with UV resistant inks to make them last even longer. Your new custom sign comes with brass grommets, that don't rust, at no extra charge. &nbsp;- you can add unlimited text, clipart, backgrounds and photographs. They can be used both indoors and outdoors. <em>If you are in the greater Columbus, OH area, we offer a "<strong>local in-store pickup</strong>" option so you can retrieve your&nbsp; custom sign order at our showroom at the corner of Wilson Rd. and Valleyview Dr. If not, shipping is with UPS and can usually ship to you in a few days.</em><em></em></p>
            <div style="text-align: center;">              
              <p class="mb-4"><a href="https://shop.customsigncenter.com/set-sized-vinyl-banners/designs/" target="_blank" title="Create Your Own custom vinyl banner"><img src="https://customsigncenter.com/images/banners/Design_Your_Own_Up.png" alt="Design Your Own vinyl banner" title="Design Your Own Custom Vinyl Banner" ></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="/quick-signs/ohio-graduation-banners" title="All Graduation Banners Categories"><img src="https://customsigncenter.com/images/banners/Graduation_Banners_Up.png" alt="Ohio Graduation Banners Categories" ></a></p>
              
              <p><a href="https://shop.customsigncenter.com/set-sized-vinyl-banners/" target="_blank" title="Choose from hundreds of templates and images from our massive library to create your custom banner."><img src="https://customsigncenter.com/images/banners/Amazing_Deals2_Up.png" alt="Custom Vinyl Banner Categories-Business | Occasions | Special Events | Sports | Holidays" id="Image14" onmouseover="this.src='/images/banners/Amazing_Deals2_Over.png';" onmouseout="this.src='/images/banners/Amazing_Deals2_Up.png';"></a>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<a href="https://shop.customsigncenter.com/military-banners/" target="_blank" title="Welcome Home Banners for All Branches of Military"><img src="https://customsigncenter.com/images/banners/special%20events/military-banners-up.jpg" alt="Custom Vinyl Banners for Military Homecomings" id="militaryrollover" onmouseover="this.src='/images/banners/special events/military-banners-dwn.jpg';" onmouseout="this.src='/images/banners/special events/military-banners-up.jpg';" width="343" height="164"></a></p>
              <p>Get started now! We've done all the hard work for you. Customize your vinyl banner today - Don't forget your <a href="https://shop.customsigncenter.com/banner-install-kit/" target="_blank" title="Banner Install kit Works well on banners up to 3' x 6'">Install Kit</a>! <br>The kit includes everything you need to erect your banner with grommets.</p>
              <h4>If you're having trouble or want more information on how to upload your own graphics, you can click through our slideshow on this feature <a href="https://1drv.ms/p/s!Amr__S7DwlJngQeTiDb58kDSa_6Y?e=AtOJkc" target="_blank" rel="noopener">here.</a></h4>
            </div>
     
@stop