<!doctype html>
<html>
<head>
<meta charset="utf-8">
	<title>Info Graphic - Types and Variety of Restaurant Signs</title>
	<meta name="robots" content="noindex">
	<style>
		body{max-width: 800px;
		max-height: 700px;}
		#wrapFloats h2{
			color:#3D5F5E;
		}
	</style>
	
	
	<link href="/css/featherlight.css" type="text/css" rel="stylesheet" />
	<!--<link href="/templates/csc-wide/css/featherlight-gallery.css" type="text/css" rel="stylesheet" />-->
	
</head>
	<body>
		
		
		
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="/images/restaurant-signs-info-graphic.png" alt="Restaurant Signs Info Graphic" usemap="#image-map">

<map name="image-map">
    <area class="featherbox-pylon" 
		  id="featherbox-pylon" 
		  data-featherlight="iframe"		  
		  data-featherlight-iframe-height="518" 
		  data-featherlight-iframe-width="585"	
		  target="" alt="Pylon Sign" title="Pylon Sign" href="index.php?option=com_content&view=article&id=169&tmpl=component" coords="95,98,49" shape="circle">
    <area class="featherbox-directional" 
		  id="featherbox-directional" 
		  data-featherlight="iframe"		  
		  data-featherlight-iframe-height="518"
		  data-featherlight-iframe-width="585"		  
		  target="" alt="Directional Signs" title="Directional Signs" href="index.php?option=com_content&view=article&id=177&tmpl=component" coords="42,302,40" shape="circle">
    <area class="featherbox-vinyl-banners" 
		  id="featherbox-vinyl-banners" 
		  data-featherlight="iframe"		  
		  data-featherlight-iframe-height="518" 
		  data-featherlight-iframe-width="585"	
		  target="" alt="Vinyl Banner" title="Vinyl Banner" href="index.php?option=com_content&view=article&id=173&tmpl=component" coords="248,219,44" shape="circle">
    <area class="featherbox-sidewalk-sign" 
		  id="featherbox-sidewalk-sign" 
		  data-featherlight="iframe"		  
		  data-featherlight-iframe-height="518" 
		  data-featherlight-iframe-width="585"	
		  target="" alt="Sidewalk and Floor Signs" title="Sidewalk and Floor Signs" href="index.php?option=com_content&view=article&id=172&tmpl=component" coords="298,345,39" shape="circle">
    <area  class="featherbox-neon-sign" 
		  id="featherbox-neon-sign" 
		  data-featherlight="iframe"		  
		  data-featherlight-iframe-height="518" 
		  data-featherlight-iframe-width="585"	
		  target="" alt="Neon Sign" title="Neon Sign" href="index.php?option=com_content&view=article&id=167&tmpl=component" coords="405,282,38" shape="circle">
    <area class="featherbox-channel-letters" 
		  data-featherlight="iframe"		  
		  data-featherlight-iframe-height="518" 
		  data-featherlight-iframe-width="585"
		  target="" alt="Channel Letter" title="Channel Letter" href="index.php?option=com_content&view=article&id=178&tmpl=component" coords="496,137,37" shape="circle">
    <area id="featherbox-wall-sign" 
		  data-featherlight="iframe"		  
		  data-featherlight-iframe-height="518" 
		  data-featherlight-iframe-width="585"
		  target="" alt="Wall Signs"
		  href="index.php?option=com_content&view=article&id=174&tmpl=component"
		  class="featherlight-wall-signs"  title="Wall Sign"  coords="558,193,34" shape="circle">
    <area class="featherbox-awnings" 
		  id="featherbox-awnings" 
		  data-featherlight="iframe"		  
		  data-featherlight-iframe-height="518" 
		  data-featherlight-iframe-width="585"	
		  target="" alt="Awning" title="Awning" href="index.php?option=com_content&view=article&id=168&tmpl=component" coords="629,229,33" shape="circle">
    <area class="featherbox-window-graphics" 
		  id="featherbox-window-graphics" 
		  data-featherlight="iframe"		  
		  data-featherlight-iframe-height="518" 
		  data-featherlight-iframe-width="585"	
		  target="" alt="Cut Vinyl Letters and Graphics" title="Cut Vinyl Letters and Graphics" href="index.php?option=com_content&view=article&id=175&tmpl=component" coords="558,299,42" shape="circle">
    <area class="featherbox-parking-signs" 
		  id="featherbox-parking-signs" 
		  data-featherlight="iframe"		  
		  data-featherlight-iframe-height="518" 
		  data-featherlight-iframe-width="585"	
		  target="" alt="Parking Sign" title="Parking Sign" href="index.php?option=com_content&view=article&id=170&tmpl=component" coords="640,378,39" shape="circle">
    <area class="featherbox-preorder-signs" 
		  id="featherbox-preorder-signs" 
		  data-featherlight="iframe"		  
		  data-featherlight-iframe-height="518" 
		  data-featherlight-iframe-width="585"	
		  target="" alt="Pre-Order Sign" title="Pre-Order Sign" href="index.php?option=com_content&view=article&id=171&tmpl=component" coords="710,333,30" shape="circle">
    <area class="featherbox-drive-thru-menu-board" 
		  id="featherbox-drive-thru-menu-board" 
		  data-featherlight="iframe"		  
		  data-featherlight-iframe-height="518" 
		  data-featherlight-iframe-width="585"	
		  target="" alt="Outdoor Menu Board" title="Outdoor Menu Board" href="index.php?option=com_content&view=article&id=176&tmpl=component" coords="796,284,40" shape="circle">
</map>		
		
<!--load jquery and featherlight lightbox plugin files -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
	
		<script src="/js/featherlight.js" type="text/javascript"></script>
  
		<!--<script src="/templates/csc-wide/js/featherlight-gallery.js" type="text/javascript"></script>-->
		<!-- support mobile devices with slide -->
		<!--<script src="/templates/csc-wide/js/jquery.detect_swipe.js" type="text/javascript"></script>-->
		<script src="//cdnjs.cloudflare.com/ajax/libs/detect_swipe/2.1.1/jquery.detect_swipe.min.js"></script>
<script>
	//no conflict mode $ alias for jQuery:
	var $ = jQuery.noConflict();	
</script>
</body>
</html>
