@extends('layouts.default')

@section('content')

<h1>Real Estate Frames | Dimensions &amp; Construction</h1>
When you need to know the dimensions size of our frames this is the place to be. All of our frames are made of 3/4" angle iron with 3/4" angle iron cross bars. The frames are painted white or black, which you'll see in the drop down when you click to order your frame. Your PVC panels and riders will slide in to their appropriate slots, no bolts, clips or other little accessories to get lost or break. Custom Sign Center produces all of our frames in house for consistent quality of construction. All of our real estate panels fit snugly in our frames. <br><br>
<ul>
<li>1/4" angle iron construction</li>
<li>1/4" angle iron cross bars</li>
<li>Painted white or black (see individual product page)</li>
<li>No bolts, clips or other accessories to get lost or break</li>
<li>Produced on-site for consistent quality of construction</li>
<li>Weight of each frame is approximately 10 pounds but can vary depending upon size and number of rider slots.</li>
</ul>
<p>Below are images of our real estate frames with dimensions listed for your review. Please visit our <a href="https://shop.customsigncenter.com/real-estate-frames-page/products/" hreflang="en-GB" dir="ltr" lang="en-GB">Frames Page</a> to order.<br><br></p>
<div style="text-align: center;"><a href="https://customsigncenter.com/images/real_estate/frames/25Frame-cBG.png" target="_blank" rel="noopener noreferrer" class="jcepopup jcemediabox-image" title="# 25 Frame" data-mediabox="1" data-mediabox-group="noreferrer" data-mediabox-title="# 25 Frame" data-mediabox-caption="18x24 in. Main Panel with 6x24 in. Bottom Rider"><img src="/images/real_estate/frames/25Frame.png" alt="18x24 in. Main Panel with 6x24 in Bottom Rider" width="199" height="258" id="Image12" title="18x24 in. Main Panel with 6x24 in. Bottom Rider" name="Image12" longdesc="#25 Frame is 18"></a> &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; <a href="https://customsigncenter.com/images/real_estate/frames/20Frame-cBG.png" target="_blank" rel="noopener noreferrer" class="jcepopup jcemediabox-image" title="# 20 Frame" data-mediabox="1" data-mediabox-group="noreferrer" data-mediabox-title="# 20 Frame" data-mediabox-caption="18x24 in Main Panel with 6x24 in Top &amp; Bottom Riders"><img src="/images/real_estate/frames/20Frame.png" alt="18x24 in. Main Panel with 6x24 in. Top &amp; Bottom Riders" width="199" height="258" id="Image13" title="# 20 Frame"></a> &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; <a href="https://customsigncenter.com/images/real_estate/frames/45Frame-cBG.png" target="_blank" rel="noopener noreferrer" class="jcepopup jcemediabox-image" title="# 45 Frame" data-mediabox="1" data-mediabox-group="noreferrer" data-mediabox-title="# 45 Frame" data-mediabox-caption="24x24 in. Main Panel with 6x24 in. Top &amp; Bottom Riders"><img src="/images/real_estate/frames/45Frame.png" alt="24x24 in. Main Panel with 6x24 in. Top &amp; Bottom Riders" width="199" height="258" id="Image13" title="# 45 Frame"></a>&nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <a href="https://customsigncenter.com/images/real_estate/frames/55Frame-cBG.png" target="_blank" rel="noopener noreferrer" class="jcepopup jcemediabox-image" title="# 55 Frame" data-mediabox="1" data-mediabox-group="noreferrer" data-mediabox-title="# 55 Frame" data-mediabox-caption="20x30 in. Main Panel with 6x30 in. Bottom Rider"><img src="/images/real_estate/frames/55Frame.png" alt="20x30 in. Main Panel with 6x30 in. Bottom Rider" width="199" height="258" title="# 55 Frame"></a></div>

<div style="text-align: center;"><a href="https://customsigncenter.com/images/real_estate/frames/40Frame-cBG.png" target="_blank" rel="noopener noreferrer" class="jcepopup jcemediabox-image" title="# 40 Frame" data-mediabox="1" data-mediabox-group="noreferrer" data-mediabox-title="# 40 Frame" data-mediabox-caption="20x30 in. Main Panel with 6x24 in. Bottom Rider"><img src="/images/real_estate/frames/40Frame.png" alt="# 40 Frame" width="199" height="258" id="Image12" title="18x24 in. Main Panel with 6x24 in. Bottom Rider" name="Image12" longdesc="#25 Frame is 18"></a> &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; <a href="https://customsigncenter.com/images/real_estate/frames/60Frame-cBG.png" target="_blank" rel="noopener noreferrer" class="jcepopup jcemediabox-image" title="# 60 Frame" data-mediabox="1" data-mediabox-group="noreferrer" data-mediabox-title="# 60 Frame" data-mediabox-caption="20x30 in Main Panel with 6x24 in Top &amp; Bottom Riders"><img src="/images/real_estate/frames/60Frame.png" alt="# 60 Frame" width="199" height="258" id="Image13" title="# 60 Frame"></a> &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; <a href="https://customsigncenter.com/images/real_estate/frames/65Frame-cBG.png" target="_blank" rel="noopener noreferrer" class="jcepopup jcemediabox-image" title="# 65 Frame" data-mediabox="1" data-mediabox-group="noreferrer" data-mediabox-title="# 65 Frame" data-mediabox-caption="20x30 in. Main Panel with 6x30 in. Top &amp; Bottom Riders"><img src="/images/real_estate/frames/65Frame.png" alt="# 65 Frame" width="199" height="258" id="Image13" title="# 65 Frame"></a>&nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <a href="https://customsigncenter.com/images/real_estate/frames/A-Frame-18x24_cBG.png" target="_blank" rel="noopener noreferrer" class="jcepopup jcemediabox-image" title="A-Frame 18x24" data-mediabox="1" data-mediabox-group="noreferrer" data-mediabox-title="A-Frame" data-mediabox-caption="A-Frame holds two 18x24 main panels"><img src="/images/real_estate/frames/A-Frame_18x24.png" alt="A Frame 18x24" width="199" height="258" title="A-Frame 18x24 in."></a></div>

<h2>Speciality Frames</h2>
<div style="text-align: center;"><a href="https://customsigncenter.com/images/real_estate/frames/72Frame-cBG.png" target="_blank" rel="noopener noreferrer" class="jcepopup jcemediabox-image" title="# 72 RE/MAX Vertical Frame" data-mediabox="1" data-mediabox-group="noreferrer" data-mediabox-title="# 72 RE/MAX Vertical Frame" data-mediabox-caption="30x24 in. Main Panel with 6x24 in. Top Rider"><img src="/images/real_estate/frames/72Frame.png" alt="72Frame" width="199" height="258" id="Image12" title="18x24 in. Main Panel with 6x24 in. Bottom Rider" name="Image12" longdesc="#25 Frame is 18"></a> &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; <a href="https://customsigncenter.com/images/real_estate/frames/70Frame-cBG.png" target="_blank" rel="noopener noreferrer" class="jcepopup jcemediabox-image" title="# 70 Frame" data-mediabox="1" data-mediabox-group="noreferrer" data-mediabox-title="# 70 RE/MAX Horizontal Frame" data-mediabox-caption="18x30 in Main Panel with 6x30 in Top &amp; Bottom Riders"><img src="/images/real_estate/frames/70Frame.png" alt="# 70 RE/MAX Horizontal Frame" width="199" height="258" id="Image13" title="# 60 Frame"></a> &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; <a href="https://customsigncenter.com/images/real_estate/frames/Flag-12x18-cBG.png" target="_blank" rel="noopener noreferrer" class="jcepopup jcemediabox-image" title="KT Flag Frame" data-mediabox="1" data-mediabox-group="noreferrer" data-mediabox-title="KT Flag Frame" data-mediabox-caption="KT Flag Frame holds 12x18 PVC or Corroplast Signs"><img src="/images/real_estate/frames/Flag-12x18.png" alt="Flag 12x18 in" width="199" height="258" id="Image13" title="12x18 Flag Frame"></a>&nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <a href="https://customsigncenter.com/images/real_estate/frames/KTFrame-cBG.png" target="_blank" rel="noopener noreferrer" class="jcepopup jcemediabox-image" title="KT Frame" data-mediabox="1" data-mediabox-group="noreferrer" data-mediabox-title="KT Frame" data-mediabox-caption="22.25 x 24 in. Main Panel with 6x24 in. Top &amp; Bottom Riders"><img src="/images/real_estate/frames/KTFrame.png" alt="#KT Frame" width="199" height="258" title="A-Frame 18x24 in."></a></div>
 

@stop
